# Generated by Django 4.2.2 on 2023-07-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('ativo', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criacao automatica')),
                ('data_hora_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data atualizada sempre que o objeto da classe é atualizado com .save')),
                ('limite_hospedes', models.IntegerField()),
                ('quant_banheiros', models.IntegerField(default=0)),
                ('aceita_animais', models.BooleanField(default=False, verbose_name='True se o imóvel aceita animais domesticos')),
                ('valor_limpeza', models.FloatField(default=0)),
                ('data_ativacao', models.DateField(null=True)),
            ],
            options={
                'db_table': 'imovel',
            },
        ),
    ]
