# Generated by Django 4.2.2 on 2023-07-01 00:41

import apps.reservas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('ativo', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criacao automatica')),
                ('data_hora_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data atualizada sempre que o objeto da classe é atualizado com .save')),
                ('codigo', models.CharField(default=apps.reservas.models.generate_random_code, editable=False, max_length=12, unique=True)),
                ('comentario', models.TextField(blank=True)),
                ('valor_total', models.FloatField(default=0)),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.anuncio', verbose_name='Anuncio que a reserva pertence')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
    ]
