# Generated by Django 4.2.2 on 2023-07-01 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlataformaAnuncio',
            fields=[
                ('ativo', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taxa', models.FloatField(default=0)),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criacao automatica')),
                ('data_hora_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data atualizada sempre que o objeto da classe é atualizado com .save')),
            ],
            options={
                'db_table': 'plataforma_anuncio',
            },
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('ativo', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criacao automatica')),
                ('data_hora_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data atualizada sempre que o objeto da classe é atualizado com .save')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel', verbose_name='Imovel que o anuncio pertence')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.plataformaanuncio', verbose_name='Plataforma que o anuncio foi publicado')),
            ],
            options={
                'db_table': 'anuncio',
            },
        ),
    ]
